### ISSUE TITLE
Trying to lazyload react-image-tooltips in Gatsby + MDX

### ISSUE THREAD

**Issue by ajmalafif** [krasnoshapka/react-image-tooltips#1]
Hey @krasnoshapka,

I was looking for this react component all over, really excited that I stumbled upon yours!

I got this error when I was trying to load this in Gatsby MDX: https://github.com/ajmalafif/afif.dev/blob/uses-afif-381/web/src/content/uses/index.mdx
![image](https://user-images.githubusercontent.com/827167/115257235-75ca6f00-a162-11eb-87d0-ad959db480df.png)

**Comment by krasnoshapka** [comment]
Hi @ajmalafif ,
Great to hear you found this package useful.
react-spring is a peer dependency. have you installed it by running 
`npm install --save react-spring react-image-tooltips
`?

**Comment by ajmalafif** [comment]
hi @krasnoshapka, yeah this is perfect for a lot of use cases!

I did, I am getting the error when I am trying to load this in MDX. I can try to do it outside MDX and see if I will have the error.

**Comment by krasnoshapka** [comment]
hi @ajmalafif ,
sorry for delay.
the reason of your problem is probably some major change in react-spring v.9, I will investigate it later. for now just install previous version:
`npm install --save react-spring@8.0.27`
this way it works for me with gatsby and mdx. here is an example component:
`import React from 'react'
import {ImageTooltips, ImageTooltipsItem, ImageTooltipsTrigger} from "react-image-tooltips"
import "react-image-tooltips/dist/index.css"
import "./tooltips.css"
import ExampleImg from '../images/example.jpg'

const Tooltips = () => {
    const MyTrigger = (<ImageTooltipsTrigger className="my-trigger">
        +
    </ImageTooltipsTrigger>);

    return (
        <ImageTooltips src={ExampleImg} width={816} height={544} className="my-image" triggerEvent="click">
            <ImageTooltipsItem top={226} left={301} trigger={MyTrigger} className="my-item">
                <p>Here's some content that lies inside an tooltip.</p>
                <p>This content can only be viewed, once the tooltip is toggled.</p>
            </ImageTooltipsItem>
            <ImageTooltipsItem top={300} left={504} trigger={MyTrigger} className="my-item">
                <p>Here's some content that lies inside an tooltip.</p>
                <p>This content can only be viewed, once the tooltip is toggled.</p>
            </ImageTooltipsItem>
        </ImageTooltips>
    );
}

export default Tooltips`
example styles can be found in https://github.com/krasnoshapka/react-image-tooltips/blob/master/example/src/styles.scss

**Comment by ajmalafif** [comment]
hey @krasnoshapka there‘s really no need for apology, I am the one who needs your help here!

I‘ve been trying to figure it out by I think my issue is that Gatsby v3 and I am using React 17 so it‘s really tricky to get this to work. 

I still can‘t make it work on MDX, I might try a way to do it without MDX and share the result of that.

here‘s my branch with its `package.json`: https://github.com/ajmalafif/afif.dev/tree/uses-afif-381

**Comment by ajmalafif** [comment]
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: sanity-gatsby-blog-web@1.0.5
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   dev react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-image-tooltips@1.3.0
npm ERR! node_modules/react-image-tooltips
npm ERR!   react-image-tooltips@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I think once this `react 17` dependencies is cleared, `react-image-tooltips` will work!

**Comment by ajmalafif** [comment]
So I just use it without MDX for now and it works!
