### ISSUE TITLE
Cannot read property 'removeEventListener' of null

### ISSUE THREAD

**Issue by ajmalafif** [krasnoshapka/react-image-tooltips#2]
I keep getting this error on localhost when I click on a page that doesn‘t have `react-image-tooltips` after i am on the page with `react-image-tooltips`

![image](https://user-images.githubusercontent.com/827167/118151359-1fd9a600-b446-11eb-9e6b-093d84157d90.png)

**Comment by krasnoshapka** [comment]
@ajmalafif I can't reproduce this so far. can you please provide more details? are you using Gatbsy? are you using react-router for multiple pages? code snippet could help as well.

**Comment by ajmalafif** [comment]
hey again @krasnoshapka! 

Yes so this is Gatsby error message. I decided to ignore this since it‘s only happening on local, while on production and deployment this isn‘t replicable and not an issue (Gatsby still compile just fine). Thank you!

Edit: Not using React Router, unless that‘s what Gatsby is using.
